name: Actualizar Datos Ganaderos FEMP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libnss3 libatk-bridge2.0-0 libgtk-3-0

      - name: Instalar dependencias Node
        run: npm install

      - name: Instalar Navegador
        run: npx puppeteer browsers install chrome
        env:
          PUPPETEER_CACHE_DIR: ${{ github.workspace }}/.cache/puppeteer

      - name: Ejecutar scraper FEMP
        run: node scraper.js
        env:
          PUPPETEER_CACHE_DIR: ${{ github.workspace }}/.cache/puppeteer

      - name: Commit y push de datos
        run: |
          git config user.name "FEMP Bot"
          git config user.email "bot@femp.local"
          git add data/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "[AUTO] Actualizacion de precios $(date +%Y-%m-%d)"
            git push
          else
            echo "No hay cambios para subir"
          fi
          echo done
